/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import HouseScene from '../assets/House_kal.glb'
import Butterfly from "../assets/butterfly.glb";
import HomeInfo from '../components/HomeInfo';
import { Html } from "@react-three/drei";


const House = ({setRotating, rotating, getStageFromHouse, ...props}) => {
    const HouseRef = useRef()
    const {gl, viewport} = useThree()
    const {nodes, materials, scene, animations} = useGLTF(HouseScene)

    const butterflyRef = useRef()
    const {butterflynodes, butterflymaterials, animations: butterflyAnimations, scene: butterflyScene} = useGLTF(Butterfly)
    const {actions, names} = useAnimations(butterflyAnimations, butterflyRef)

    const [idleRotation, setIdleRotation] = useState(0.001)
    const [stage, setStage] = useState(0)
    const lastX = useRef(0)
    const rotationSpeed = useRef(0)
    const dampingFactor = 0.95

    getStageFromHouse(stage)

    const handleMouseDown =(e)=>{
        e.stopPropagation()
        e.preventDefault()
        setRotating(true);
        const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    }
    const handleMouseUp =(e)=>{
        e.stopPropagation()
        e.preventDefault()
        setRotating(false);
    }
    const handleMouseMove =(e)=>{
        e.stopPropagation()
        e.preventDefault()
        if (rotating) {
            const clientX = e.touches ? e.touches[0].clientX : e.clientX;
            const delta = (clientX - lastX.current) * 0.1
            HouseRef.current.rotation.y += delta * 0.01 * Math.PI;
            lastX.current = clientX;
            rotationSpeed.current = delta * 0.01 * Math.PI;
        }else if (!rotating){
            const clientX = e.clientX
            lastX.current = clientX
        }

    }
    const handleKeyDown =(e)=>{
        if(e.key === 'ArrowLeft') {
            if(!rotating) setRotating(true);
            rotationSpeed.current = 0.09;
        } else if (e.key === 'ArrowRight') {
            if(!rotating) setRotating(true);
            rotationSpeed.current = -0.09;
        }
        else if (e.key === 'ArrowUp') {
            if(!rotating) setRotating(true);
            HouseRef.current.rotation.x += 0.05 * Math.PI;
            if (HouseRef.current.rotation.x > 0.57) {
                setRotating(false)
                HouseRef.current.rotation.x = 0.57
            }
        }
        else if (e.key === 'ArrowDown') {
            if(!rotating) setRotating(true);
            HouseRef.current.rotation.x -= 0.05 * Math.PI;
            if (HouseRef.current.rotation.x < -0.2) {
                setRotating(false)
                HouseRef.current.rotation.x = -0.2
            }
        }
    }
    const handleKeyUp=(e)=>{
        setRotating(false)
    }

    useFrame(()=>{
        if(!rotating) {
            rotationSpeed.current *= dampingFactor;
            //rotates the house when idle
            HouseRef.current.rotation.y -= (5%2)*idleRotation
            if(HouseRef.current.rotation.y < -100) {
              setIdleRotation(0)
              HouseRef.current.rotation.y = 0
            }
            // console.log(`${HouseRef.current.rotation.y} ||| ${idleRotation}`)
            if (Math.abs(rotationSpeed.current) < 0.001) {
                rotationSpeed.current = 0;
            }
                HouseRef.current.rotation.y += rotationSpeed.current;
            }

            const rotation = HouseRef.current.rotation.y
            const normalizeRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI)%(2*Math.PI);
            // console.log(normalizeRotation)
            if (normalizeRotation > 0.5 && normalizeRotation < 1.2){
              setStage('1')
            } else if (normalizeRotation > 5.4 && normalizeRotation < 6.0){
              setStage('2')
            } else if (normalizeRotation > 3.5 && normalizeRotation < 4.2){
              setStage('3')
            } else if (normalizeRotation > 1.7 && normalizeRotation < 2.4){
              setStage('4')
            }else{
              setStage(0)
            }
            // console.log(normalizeRotation)
    });

    useEffect(()=>{
        actions[names[0]].play()
        const canvas = gl.domElement;
        canvas.addEventListener('pointerdown', handleMouseDown);
        canvas.addEventListener('pointerup', handleMouseUp)
        canvas.addEventListener('pointermove', handleMouseMove)
        document.addEventListener('keydown', handleKeyDown)
        document.addEventListener('keyup', handleKeyUp)

        return ()=>{
            canvas.removeEventListener('pointerdown', handleMouseDown);
            canvas.removeEventListener('pointerup', handleMouseUp)
            canvas.removeEventListener('pointermove', handleMouseMove)
            document.removeEventListener('keydown', handleKeyDown)
            document.removeEventListener('keyup', handleKeyUp)

        }
    }, [gl, handleMouseDown, handleMouseMove, handleMouseUp])

  return (
    <a.group {...props} ref={HouseRef} castShadow >
        {/* <a.primitive object={scene} castShadow receiveShadow/> */}
        <a.group  ref={butterflyRef} castShadow receiveShadow>
        <primitive position={[3, 3, 4]} scale={[0.3, 0.3, 0.3]} rotation={[0, 0.5, 1]} object={butterflyScene} castShadow receiveShadow/>
        </a.group>

        <group position={[0.381, -0.01, 3.797]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pitcher3_1.geometry}
          material={materials["Mat.1"]}
          position={[-0.149, 0.01, 0.358]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pitcher1_1.geometry}
          material={materials["Mat.1"]}
          position={[0.113, 0.018, -0.242]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pitcher2_1.geometry}
          material={materials.Mat}
          position={[-0.074, -0.009, -0.429]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pitcher4_1.geometry}
          material={materials.Mat}
          position={[0.122, -0.009, 0.281]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pitcher_1.geometry}
          material={materials.Mat}
          position={[-0.014, -0.009, 0.032]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rose.geometry}
        material={nodes.Rose.material}
        position={[-0.925, 1.195, 1.627]}
      >
        <group position={[0, -0.814, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Disc1_0.geometry}
            material={nodes.Disc1_0.material}
            position={[0, 0, 0.311]}
            rotation={[Math.PI, 1.501, 2.793]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Disc1_1.geometry}
            material={nodes.Disc1_1.material}
            position={[-0.295, 0, 0.096]}
            rotation={[0, 0.384, -Math.PI / 9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Disc1_2.geometry}
            material={nodes.Disc1_2.material}
            position={[-0.183, 0, -0.251]}
            rotation={[0, -0.873, -Math.PI / 9]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Disc1_3.geometry}
            material={nodes.Disc1_3.material}
            position={[0.183, 0, -0.251]}
            rotation={[-Math.PI, -1.012, 2.793]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Disc1_4.geometry}
            material={nodes.Disc1_4.material}
            position={[0.295, 0, 0.096]}
            rotation={[-Math.PI, 0.244, 2.793]}
          />
        </group>
      </mesh>
      <group position={[0, -1.547, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["podstavka-Mat_1"].geometry}
          material={materials.Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["podstavka-elki2_1"].geometry}
          material={materials.elki2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["podstavka-elki2_3"].geometry}
          material={materials.elki2}
        />
      </group>
      <group position={[-1.022, 0.342, 3.208]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bushFront.geometry}
          material={materials.elki}
          position={[7.532, -0.021, -2.144]}
        />
        <group position={[-5.188, 0.045, 0.811]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw1_1.geometry}
            material={materials.elki2}
            position={[-0.256, -0.108, 0.217]}
            rotation={[0, 0, 0.235]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw_1.geometry}
            material={materials.elki2}
            position={[0.086, 0.243, -0.449]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw7_1.geometry}
            material={materials.elki2}
            position={[0.17, -0.135, 0.231]}
            rotation={[0.339, 0, 0]}
          />
        </group>
        <group
          position={[3.245, -0.047, 6.014]}
          rotation={[-3.017, 0.487, Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw1_3.geometry}
            material={materials.elki2}
            position={[0.272, -0.1, -0.18]}
            rotation={[-0.353, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw3_1.geometry}
            material={materials.elki2}
            position={[0.515, -0.272, 0.092]}
            rotation={[-1.332, -1.286, -1.416]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw2_1.geometry}
            material={materials.elki}
            position={[-0.16, -0.145, -0.234]}
            rotation={[2.362, -0.914, 2.524]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw_3.geometry}
            material={materials.elki2}
            position={[-0.042, 0.181, 0.414]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw4_1.geometry}
            material={materials.elki}
            position={[0.492, -0.142, -0.408]}
            rotation={[-0.613, -0.936, -0.556]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw5_1.geometry}
            material={materials.elki2}
            position={[-0.346, 0.008, 0.003]}
            rotation={[-2.53, -0.804, -2.847]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw6_1.geometry}
            material={materials.elki}
            position={[-0.471, -0.14, 0.356]}
            rotation={[-2.225, 0.892, 2.416]}
          />
        </group>
        <group position={[-6.642, -0.014, -8.347]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw1_5.geometry}
            material={materials.elki2}
            position={[0.37, -0.109, -0.245]}
            rotation={[-0.353, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw3_3.geometry}
            material={materials.elki2}
            position={[0.763, -0.121, 0.142]}
            rotation={[-1.332, -1.286, -1.416]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw2_3.geometry}
            material={materials.elki}
            position={[-0.218, -0.158, -0.318]}
            rotation={[2.362, -0.914, 2.524]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw_5.geometry}
            material={materials.elki2}
            position={[-0.058, 0.196, 0.563]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw4_3.geometry}
            material={materials.elki}
            position={[0.94, -0.246, -0.717]}
            rotation={[-0.613, -0.936, -0.556]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw5_3.geometry}
            material={materials.elki2}
            position={[-1.055, -0.102, 0.649]}
            rotation={[-2.53, -0.804, -2.847]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw6_3.geometry}
            material={materials.elki}
            position={[-0.664, -0.185, 1.192]}
            rotation={[-3.087, 1.11, -3.138]}
          />
        </group>
        <group position={[8.585, 0.017, 1.522]} rotation={[0, 0.182, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw1_7.geometry}
            material={materials.elki}
            position={[-0.47, 0.051, 1.624]}
            rotation={[-0.353, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw3_5.geometry}
            material={materials.elki}
            position={[0.172, -0.121, 1.317]}
            rotation={[-1.388, -0.442, -1.684]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw2_5.geometry}
            material={materials.elki2}
            position={[0.916, -0.158, 0.272]}
            rotation={[2.094, -0.96, 2.583]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw_7.geometry}
            material={materials.elki}
            position={[-0.058, 0.196, 0.563]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw4_5.geometry}
            material={materials.elki2}
            position={[0.659, -0.042, 0.665]}
            rotation={[-2.091, -0.371, -1.872]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw5_5.geometry}
            material={materials.elki2}
            position={[-1.055, -0.102, 0.649]}
            rotation={[-2.53, -0.804, -2.847]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bushes_sw6_5.geometry}
            material={materials.elki2}
            position={[-0.837, -0.185, 2.132]}
            rotation={[-0.029, 0.551, 0.068]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kamyshi_trava2.geometry}
        material={materials.elki}
        position={[2.128, 0.118, -9.252]}
        rotation={[0, -0.721, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kamyshi_trava1.geometry}
        material={materials.elki}
        position={[-4.858, 0.148, 3.964]}
        rotation={[0, -0.721, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kamyshi_trava.geometry}
        material={materials.elki}
        position={[3.44, 0.164, 5.558]}
        rotation={[0, -0.721, 0]}
      />
      <group position={[-2.5, 5.963, 4.068]} rotation={[0, 0.291, 0]}>
        <group
          position={[-0.221, 0.017, 0.122]}
          rotation={[2.741, -0.263, 3.032]}
          scale={[3.787, 10.514, 7.418]}
        >
          <group position={[0, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_0.geometry}
              material={materials["Mat.13"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_1.geometry}
              material={materials["Mat.12"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_2.geometry}
              material={materials["Mat.7"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials["Mat.13"]}
            />
          </group>
          <group position={[-0.093, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4_1.geometry}
              material={materials["Mat.13"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5_1.geometry}
              material={materials["Mat.13"]}
            />
          </group>
          <group position={[0.093, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_1.geometry}
              material={materials["Mat.13"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7_1.geometry}
              material={materials["Mat.13"]}
            />
          </group>
        </group>
        <group
          position={[0.304, -0.051, -0.022]}
          rotation={[2.755, 0.046, -3.123]}
          scale={[3.787, 10.514, 7.418]}
        >
          <group position={[-0.054, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4_3.geometry}
              material={materials["Mat.13"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5_3.geometry}
              material={materials["Mat.13"]}
            />
          </group>
          <group position={[0.054, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_3.geometry}
              material={materials["Mat.13"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7_3.geometry}
              material={materials["Mat.13"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_0_1.geometry}
            material={materials["Mat.13"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_1_1.geometry}
            material={materials["Mat.12"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2_1.geometry}
            material={materials["Mat.7"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3_1.geometry}
            material={materials["Mat.13"]}
          />
        </group>
        <group position={[-0.083, 0.033, -0.1]} rotation={[0, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Nest-Mat1_1"].geometry}
            material={materials["Mat.1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Nest-Mat_1"].geometry}
            material={materials.Mat}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.path.geometry}
        material={materials.elki}
        position={[4.886, 0.101, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Extrude.geometry}
          material={materials.Mat}
          position={[-4.886, -1.568, 0]}
        />
      </mesh>
      <group position={[0, -1.687, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["charcoal-Mat"].geometry}
          material={materials.Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["charcoal-Mat7"].geometry}
          material={materials["Mat.7"]}
        />
        <group position={[4.194, 1.88, -4.849]} rotation={[0, 0.686, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere3.geometry}
            material={materials.Mat}
            position={[-0.372, 0, -0.438]}
            rotation={[0, 0.755, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere2.geometry}
            material={materials.Mat}
            position={[0.188, 0, 0.927]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere1.geometry}
            material={materials.Mat}
            position={[0.188, 0, -0.704]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
            material={materials.Mat}
            position={[-0.004, 0, 0.215]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fire_1.geometry}
          material={materials["Mat.1"]}
          position={[5.001, 1.876, -5.535]}
        />
      </group>
      <group position={[-5.57, 0.788, 1.914]}>
        <group position={[0, 0.505, -0.005]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["barrel2-Mat2_1"].geometry}
            material={materials["Mat.2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["barrel2-Mat1_1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[0, -0.253, 0.423]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["barrel1-Mat2_1"].geometry}
            material={materials["Mat.2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["barrel1-Mat1_1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[0, -0.253, -0.418]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["barrel-Mat2_1"].geometry}
            material={materials["Mat.2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["barrel-Mat1_1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
      </group>
      <group position={[-9.409, 1.601, 0.158]}>
        <group
          position={[-0.311, -1.724, 1.937]}
          rotation={[0.122, -1.459, -0.117]}
        >
          <group
            position={[-0.06, -0.083, 0.163]}
            rotation={[0.239, -0.188, 0.211]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["mushroom2-Mat2"].geometry}
              material={materials["Mat.2"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["mushroom2-Mat"].geometry}
              material={materials.Mat}
            />
          </group>
          <group
            position={[-0.127, 0.103, 0.001]}
            rotation={[-0.078, -0.433, 0.099]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["mushroom1-Mat2"].geometry}
              material={materials["Mat.2"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["mushroom1-Mat"].geometry}
              material={materials.Mat}
            />
          </group>
          <group
            position={[0.187, -0.021, -0.163]}
            rotation={[0.275, 0.376, -0.041]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["mushroom-Mat2"].geometry}
              material={materials["Mat.2"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["mushroom-Mat"].geometry}
              material={materials.Mat}
            />
          </group>
        </group>
        <group position={[-0.76, -1.16, 0.361]} rotation={[0, -0.577, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.elka1_2.geometry}
            material={nodes.elka1_2.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["elka1-elki_1"].geometry}
            material={materials.elki}
          />
        </group>
        <group
          position={[0.29, -0.705, 0.695]}
          rotation={[0.602, 1.439, -0.729]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.elka2_2.geometry}
            material={nodes.elka2_2.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["elka2-elki_1"].geometry}
            material={materials.elki}
          />
        </group>
        <group position={[0.469, 1.77, -1.057]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            position={[-0.205, -3.602, 0.349]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone7.geometry}
            material={materials.elki}
            position={[-0.256, 1.939, 0.314]}
            rotation={[0.293, -0.027, 0.375]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone6.geometry}
            material={materials.elki}
            position={[-0.021, 1.366, 0.147]}
            rotation={[0.293, -0.027, 0.375]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone5.geometry}
            material={materials.elki}
            position={[-0.04, 0.822, -0.136]}
            rotation={[-0.07, -0.027, 0.375]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone4.geometry}
            material={materials.elki}
            position={[0.114, 0.31, -0.129]}
            rotation={[-0.072, -0.02, 0.272]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone3.geometry}
            material={materials.elki}
            position={[0.141, -0.173, -0.092]}
            rotation={[0.043, 0.002, -0.023]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone2.geometry}
            material={materials.elki}
            position={[0.082, -0.726, -0.051]}
            rotation={[0.031, -0.004, 0.055]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone1.geometry}
            material={materials.elki}
            position={[0.037, -1.41, -0.092]}
            rotation={[-0.075, -0.004, 0.055]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cone.geometry}
            material={materials.elki}
            position={[-0.057, -2.127, 0.039]}
            rotation={[-0.075, 0, 0]}
          />
        </group>
      </group>
      <group
        position={[-5.671, 0.317, -2.714]}
        rotation={[-Math.PI, 0.058, -Math.PI]}
      >
        <group position={[0, 0.367, -0.006]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder9-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder9-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[0, 0.191, -0.137]} rotation={[0, 0.03, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder8-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder8-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0, 0.202, 0.147]}
          rotation={[0, -0.034, -Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder7-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder7-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[0, 0, 0.273]} rotation={[0, 0, -1.6]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder6-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder6-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[0, 0.01, 0.008]} rotation={[0, 0, -1.541]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder5-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder5-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[0, -0.011, -0.272]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder4-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder4-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0, -0.193, -0.413]}
          rotation={[0, 0.02, -Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder3-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder3-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0, -0.188, -0.133]}
          rotation={[0, -0.046, -Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder2-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder2-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0, -0.188, 0.142]}
          rotation={[0, 0.044, -Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder1-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder1-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0, -0.188, 0.391]}
          rotation={[0, -0.093, -Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Cylinder-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
      </group>
      <group position={[-2.449, 0.15, 0.308]}>
        <group
          position={[2.965, 0.092, 0.375]}
          rotation={[-Math.PI, 0.218, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers-Mat2"].geometry}
            material={materials["Mat.2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers-elki"].geometry}
            material={materials.elki}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-5.906, -0.243, 4.846]}
          rotation={[-Math.PI, 1.059, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet2-elki"].geometry}
            material={materials.elki}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet2-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet2-Mat2"].geometry}
            material={materials["Mat.2"]}
          />
        </group>
        <group
          position={[5.668, 0.15, 5.705]}
          rotation={[Math.PI, 0.776, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet-elki"].geometry}
            material={materials.elki}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet-Mat2"].geometry}
            material={materials["Mat.2"]}
          />
        </group>
        <group position={[-2.498, 0.15, -5.846]} rotation={[0, 0.774, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet1-elki"].geometry}
            material={materials.elki}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet1-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["camBoquet1-Mat2"].geometry}
            material={materials["Mat.2"]}
          />
        </group>
        <group
          position={[5.201, 0.092, -9.741]}
          rotation={[Math.PI, -1.245, Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers2-Mat2"].geometry}
            material={materials["Mat.2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers2-elki"].geometry}
            material={materials.elki}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers2-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[-5.431, -0.242, 4.66]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers1-Mat2"].geometry}
            material={materials["Mat.2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers1-elki"].geometry}
            material={materials.elki}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["redFlowers1-Mat1"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
      </group>
      <group
        position={[-2.034, 0.713, -6.918]}
        rotation={[-0.025, -0.106, 0.013]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["car1-Mat"].geometry}
          material={materials.Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["car1-elki"].geometry}
          material={materials.elki}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["car1-Mat_1"].geometry}
          material={materials.Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["car1-Mat2"].geometry}
          material={materials["Mat.2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["car1-Mat1"].geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["car1-Mat1_1"].geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["car1-Mat2_1"].geometry}
          material={materials["Mat.2"]}
        />
      </group>
      <group position={[-1.104, 0.387, 6.37]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Gryadka_s_klubnik0oi1-elki2_1"].geometry}
          material={materials.elki2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Gryadka_s_klubnik0oi1-elki_1"].geometry}
          material={materials.elki}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Gryadka_s_klubnik0oi1-Mat2_1"].geometry}
          material={materials["Mat.2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.zabor4_1.geometry}
          material={materials["Mat.1"]}
          position={[-0.003, -0.059, 0.079]}
        />
      </group>
      <group position={[4.69, 0.497, 2.209]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pumpkins1-Mat1"].geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["pumpkins1-elki"].geometry}
          material={materials.elki}
        />
      </group>
      <group position={[4.253, 0.899, 4.16]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["kolodec1-Mat1"].geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["kolodec1-Mat2"].geometry}
          material={materials["Mat.2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["kolodec1-Mat"].geometry}
          material={materials.Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bucket.geometry}
          material={materials["Mat.1"]}
          position={[-1.58, -0.888, 0.801]}
          rotation={[0, -0.525, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sweep_1.geometry}
            material={materials["Mat.1"]}
            position={[0.006, -0.161, -8.255]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KolKryshka.geometry}
          material={materials["Mat.1"]}
          position={[-0.487, 1.135, 1.474]}
        />
      </group>
      <group position={[1.529, 2.878, -1.696]}>
        <group
          position={[6.102, 0.242, -0.29]}
          rotation={[Math.PI, -0.038, Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Apple_tree1-Mat"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Apple_tree1-Mat_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Apple_tree1-Mat2"].geometry}
            material={materials["Mat.2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Apple_tree1-elki"].geometry}
            material={materials.elki}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Apple_tree1-Mat2_1"].geometry}
            material={materials["Mat.2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bush2.geometry}
            material={materials.elki2}
            position={[0.53, -2.887, -0.456]}
            rotation={[-Math.PI, 0.038, -Math.PI]}
          />
        </group>
        <group
          position={[0.65, -1.028, -6.899]}
          rotation={[-Math.PI, 0.384, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Birch1-Mat_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Birch1-elki2_1"].geometry}
            material={materials.elki2}
          />
        </group>
        <group position={[-7.028, 0.807, 7.2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Birch-Mat_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Birch-elki2_1"].geometry}
            material={materials.elki2}
          />
        </group>
      </group>
      <group position={[-1.114, 5.483, -1.849]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["House1-Mat"].geometry}
          material={materials.Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["House1-Mat_1"].geometry}
          material={materials.Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["House1-Mat2"].geometry}
          material={materials["Mat.2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["House1-elki"].geometry}
          material={materials.elki}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["House1-Mat1"].geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["House1-Mat2_1"].geometry}
          material={materials["Mat.2"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.oblako_1.geometry}
        material={materials.elki}
        position={[0, -0.679, 0]}
        rotation={[0, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone1_1.geometry}
        material={materials.Mat}
        position={[-7.319, -0.038, 5.471]}
        rotation={[0.227, 0, 0]}
      />
    </a.group>
    );
}


export default House;
