/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 src/assets/House_kal.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/House_kal.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1.547, 0]}>
        <mesh geometry={nodes['podstavka-Mat6_1'].geometry} material={materials['Mat.6']} />
        <mesh geometry={nodes['podstavka-Mat_2'].geometry} material={materials.Mat} />
        <mesh geometry={nodes['podstavka-Mat_3'].geometry} material={materials.Mat} />
      </group>
      <group position={[-6.21, 0.387, 4.019]}>
        <mesh geometry={nodes.bushes_sw1_3.geometry} material={materials.elki2} position={[-0.256, -0.108, 0.217]} rotation={[0, 0, 0.235]} />
        <mesh geometry={nodes.bushes_sw_3.geometry} material={materials.elki2} position={[0.086, 0.243, -0.449]} />
        <mesh geometry={nodes.bushes_sw7_1.geometry} material={materials.elki2} position={[0.17, -0.135, 0.231]} rotation={[0.339, 0, 0]} />
      </group>
      <group position={[-7.664, 0.327, -5.139]}>
        <mesh geometry={nodes.bushes_sw1_4.geometry} material={materials.elki2} position={[0.37, -0.109, -0.245]} rotation={[-0.353, 0, 0]} />
        <mesh geometry={nodes.bushes_sw3_2.geometry} material={materials.elki2} position={[0.763, -0.121, 0.142]} rotation={[-1.332, -1.286, -1.416]} />
        <mesh geometry={nodes.bushes_sw2_2.geometry} material={materials.elki} position={[-0.218, -0.158, -0.318]} rotation={[2.362, -0.914, 2.524]} />
        <mesh geometry={nodes.bushes_sw_4.geometry} material={materials.elki2} position={[-0.058, 0.196, 0.563]} />
        <mesh geometry={nodes.bushes_sw4_2.geometry} material={materials.elki} position={[0.94, -0.246, -0.717]} rotation={[-0.613, -0.936, -0.556]} />
        <mesh geometry={nodes.bushes_sw5_2.geometry} material={materials.elki2} position={[-1.055, -0.102, 0.649]} rotation={[-2.53, -0.804, -2.847]} />
        <mesh geometry={nodes.bushes_sw6_2.geometry} material={materials.elki} position={[-0.664, -0.185, 1.192]} rotation={[-3.087, 1.11, -3.138]} />
      </group>
      <group position={[7.563, 0.358, 4.73]} rotation={[0, 0.182, 0]}>
        <mesh geometry={nodes.bushes_sw1_5.geometry} material={materials.elki} position={[-0.47, 0.051, 1.624]} rotation={[-0.353, 0, 0]} />
        <mesh geometry={nodes.bushes_sw3_3.geometry} material={materials.elki} position={[0.172, -0.121, 1.317]} rotation={[-1.388, -0.442, -1.684]} />
        <mesh geometry={nodes.bushes_sw2_3.geometry} material={materials.elki2} position={[0.916, -0.158, 0.272]} rotation={[2.094, -0.96, 2.583]} />
        <mesh geometry={nodes.bushes_sw_5.geometry} material={materials.elki} position={[-0.058, 0.196, 0.563]} />
        <mesh geometry={nodes.bushes_sw4_3.geometry} material={materials.elki2} position={[0.659, -0.042, 0.665]} rotation={[-2.091, -0.371, -1.872]} />
        <mesh geometry={nodes.bushes_sw5_3.geometry} material={materials.elki2} position={[-1.055, -0.102, 0.649]} rotation={[-2.53, -0.804, -2.847]} />
        <mesh geometry={nodes.bushes_sw6_3.geometry} material={materials.elki2} position={[-0.837, -0.185, 2.132]} rotation={[-0.029, 0.551, 0.068]} />
      </group>
      <group position={[-2.5, 5.963, 0.212]}>
        <group position={[-0.221, 0.017, 0.122]} rotation={[2.741, -0.263, 3.032]} scale={[3.787, 10.514, 7.418]}>
          <group position={[0, 0, 0]}>
            <mesh geometry={nodes.Object_0.geometry} material={materials['Mat.13']} />
            <mesh geometry={nodes.Object_1.geometry} material={materials['Mat.12']} />
            <mesh geometry={nodes.Object_2.geometry} material={materials['Mat.7']} />
            <mesh geometry={nodes.Object_3.geometry} material={materials['Mat.13']} />
          </group>
          <group position={[-0.093, 0, 0]}>
            <mesh geometry={nodes.Object_4_2.geometry} material={materials['Mat.13']} />
            <mesh geometry={nodes.Object_5_2.geometry} material={materials['Mat.13']} />
          </group>
          <group position={[0.093, 0, 0]}>
            <mesh geometry={nodes.Object_6_2.geometry} material={materials['Mat.13']} />
            <mesh geometry={nodes.Object_7_2.geometry} material={materials['Mat.13']} />
          </group>
        </group>
        <group position={[0.304, -0.051, -0.022]} rotation={[2.755, 0.046, -3.123]} scale={[3.787, 10.514, 7.418]}>
          <group position={[-0.054, 0, 0]}>
            <mesh geometry={nodes.Object_4_3.geometry} material={materials['Mat.13']} />
            <mesh geometry={nodes.Object_5_3.geometry} material={materials['Mat.13']} />
          </group>
          <group position={[0.054, 0, 0]}>
            <mesh geometry={nodes.Object_6_3.geometry} material={materials['Mat.13']} />
            <mesh geometry={nodes.Object_7_3.geometry} material={materials['Mat.13']} />
          </group>
          <mesh geometry={nodes.Object_0_1.geometry} material={materials['Mat.13']} />
          <mesh geometry={nodes.Object_1_1.geometry} material={materials['Mat.12']} />
          <mesh geometry={nodes.Object_2_1.geometry} material={materials['Mat.7']} />
          <mesh geometry={nodes.Object_3_1.geometry} material={materials['Mat.13']} />
        </group>
        <group position={[-0.083, 0.033, -0.1]} rotation={[0, 0, -Math.PI]}>
          <mesh geometry={nodes['Nest-Mat14_1'].geometry} material={materials['Mat.14']} />
          <mesh geometry={nodes['Nest-Mat11_1'].geometry} material={materials['Mat.11']} />
        </group>
      </group>
      <group position={[0, -1.687, 0]}>
        <group position={[4.194, 1.88, -4.849]} rotation={[0, 0.686, 0]}>
          <mesh geometry={nodes.Sphere3.geometry} material={materials.stone1} position={[-0.372, 0, -0.438]} rotation={[0, 0.755, 0]} />
          <mesh geometry={nodes.Sphere2.geometry} material={materials.stone1} position={[0.188, 0, 0.927]} />
          <mesh geometry={nodes.Sphere1.geometry} material={materials.stone1} position={[0.188, 0, -0.704]} />
          <mesh geometry={nodes.Sphere.geometry} material={materials.stone1} position={[-0.004, 0, 0.215]} />
        </group>
        <mesh geometry={nodes['charcoal-Mat10'].geometry} material={materials['Mat.10']} />
        <mesh geometry={nodes['charcoal-Mat7'].geometry} material={materials['Mat.7']} />
        <mesh geometry={nodes.fire_1.geometry} material={materials['Mat.8']} position={[5.001, 1.876, -5.535]} />
      </group>
      <group position={[-5.57, 0.788, 1.914]}>
        <group position={[0, 0.505, -0.005]}>
          <mesh geometry={nodes['barrel2-Mat8_1'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['barrel2-Mat7_1'].geometry} material={materials['Mat.7']} />
        </group>
        <group position={[0, -0.253, 0.423]}>
          <mesh geometry={nodes['barrel1-Mat8_1'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['barrel1-Mat7_1'].geometry} material={materials['Mat.7']} />
        </group>
        <group position={[0, -0.253, -0.418]}>
          <mesh geometry={nodes['barrel-Mat8_1'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['barrel-Mat7_1'].geometry} material={materials['Mat.7']} />
        </group>
      </group>
      <group position={[-5.671, 0.317, -2.714]} rotation={[-Math.PI, 0.058, Math.PI]}>
        <group position={[0, 0.367, -0.006]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes['Cylinder9-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder9-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, 0.191, -0.137]} rotation={[0, 0.03, -Math.PI / 2]}>
          <mesh geometry={nodes['Cylinder8-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder8-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, 0.202, 0.147]} rotation={[0, -0.034, -Math.PI / 2]}>
          <mesh geometry={nodes['Cylinder7-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder7-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, 0, 0.273]} rotation={[0, 0, -1.6]}>
          <mesh geometry={nodes['Cylinder6-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder6-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, 0.01, 0.008]} rotation={[0, 0, -1.541]}>
          <mesh geometry={nodes['Cylinder5-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder5-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, -0.011, -0.272]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes['Cylinder4-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder4-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, -0.193, -0.413]} rotation={[0, 0.02, -Math.PI / 2]}>
          <mesh geometry={nodes['Cylinder3-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder3-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, -0.188, -0.133]} rotation={[0, -0.046, -Math.PI / 2]}>
          <mesh geometry={nodes['Cylinder2-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder2-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, -0.188, 0.142]} rotation={[0, 0.044, -Math.PI / 2]}>
          <mesh geometry={nodes['Cylinder1-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder1-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
        <group position={[0, -0.188, 0.391]} rotation={[0, -0.093, -Math.PI / 2]}>
          <mesh geometry={nodes['Cylinder-Mat8'].geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes['Cylinder-Mat11'].geometry} material={materials['Mat.11']} />
        </group>
      </group>
      <group position={[0.516, 0.242, 0.683]} rotation={[-Math.PI, 0.218, -Math.PI]}>
        <mesh geometry={nodes['redFlowers-elki'].geometry} material={materials.elki} />
        <mesh geometry={nodes['redFlowers-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['redFlowers-strawberry'].geometry} material={materials.strawberry} />
      </group>
      <group position={[-9.72, -0.123, 2.095]} rotation={[0.122, -1.459, -0.117]}>
        <group position={[-0.06, -0.083, 0.163]} rotation={[0.239, -0.188, 0.211]}>
          <mesh geometry={nodes['mushroom2-Mat6'].geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes['mushroom2-Mat10'].geometry} material={materials['Mat.10']} />
        </group>
        <group position={[-0.127, 0.103, 0.001]} rotation={[-0.078, -0.433, 0.099]}>
          <mesh geometry={nodes['mushroom1-Mat6'].geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes['mushroom1-Mat10'].geometry} material={materials['Mat.10']} />
        </group>
        <group position={[0.187, -0.021, -0.163]} rotation={[0.275, 0.376, -0.041]}>
          <mesh geometry={nodes['mushroom-Mat6'].geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes['mushroom-Mat10'].geometry} material={materials['Mat.10']} />
        </group>
      </group>
      <group position={[-8.355, -0.094, 5.154]} rotation={[-Math.PI, 1.059, -Math.PI]}>
        <mesh geometry={nodes['camBoquet2-elki'].geometry} material={materials.elki} />
        <mesh geometry={nodes['camBoquet2-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['camBoquet2-Mat9'].geometry} material={materials['Mat.9']} />
      </group>
      <group position={[3.218, 0.3, 6.012]} rotation={[Math.PI, 0.776, -Math.PI]}>
        <mesh geometry={nodes['camBoquet-elki'].geometry} material={materials.elki} />
        <mesh geometry={nodes['camBoquet-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['camBoquet-Mat9'].geometry} material={materials['Mat.9']} />
      </group>
      <group position={[-4.948, 0.3, -5.538]} rotation={[0, 0.774, 0]}>
        <mesh geometry={nodes['camBoquet1-elki'].geometry} material={materials.elki} />
        <mesh geometry={nodes['camBoquet1-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['camBoquet1-Mat9'].geometry} material={materials['Mat.9']} />
      </group>
      <group position={[2.752, 0.242, -9.434]} rotation={[Math.PI, -1.245, Math.PI]}>
        <mesh geometry={nodes['redFlowers2-elki'].geometry} material={materials.elki} />
        <mesh geometry={nodes['redFlowers2-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['redFlowers2-strawberry'].geometry} material={materials.strawberry} />
      </group>
      <group position={[-7.881, -0.092, 4.968]}>
        <mesh geometry={nodes['redFlowers1-elki'].geometry} material={materials.elki} />
        <mesh geometry={nodes['redFlowers1-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['redFlowers1-strawberry'].geometry} material={materials.strawberry} />
      </group>
      <group position={[-2.034, 0.713, -6.918]} rotation={[-0.025, -0.106, 0.013]}>
        <mesh geometry={nodes['car1-glass'].geometry} material={materials.glass} />
        <mesh geometry={nodes['car1-glass_1'].geometry} material={materials.glass} />
        <mesh geometry={nodes['car1-Mat9'].geometry} material={materials['Mat.9']} />
        <mesh geometry={nodes['car1-stone1'].geometry} material={materials.stone1} />
        <mesh geometry={nodes['car1-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['car1-Mat3'].geometry} material={materials['Mat.3']} />
        <mesh geometry={nodes['car1-Mat7'].geometry} material={materials['Mat.7']} />
      </group>
      <group position={[-9.409, 1.601, 0.158]}>
        <group position={[-0.76, -1.065, 0.361]} rotation={[0, -0.577, 0]}>
          <mesh geometry={nodes['elka1-Mat6_1'].geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes['elka1-elki_1'].geometry} material={materials.elki} />
        </group>
        <group position={[0.29, -0.705, 0.695]} rotation={[0.602, 1.439, -0.729]}>
          <mesh geometry={nodes['elka2-Mat6_1'].geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes['elka2-elki_1'].geometry} material={materials.elki} />
        </group>
        <group position={[0.469, 1.77, -1.057]}>
          <mesh geometry={nodes.Cube.geometry} material={materials['Mat.6']} position={[-0.205, -3.602, 0.349]} />
          <mesh geometry={nodes.Cone7.geometry} material={materials.elki} position={[-0.256, 1.939, 0.314]} rotation={[0.293, -0.027, 0.375]} />
          <mesh geometry={nodes.Cone6.geometry} material={materials.elki} position={[-0.021, 1.366, 0.147]} rotation={[0.293, -0.027, 0.375]} />
          <mesh geometry={nodes.Cone5.geometry} material={materials.elki} position={[-0.04, 0.822, -0.136]} rotation={[-0.07, -0.027, 0.375]} />
          <mesh geometry={nodes.Cone4.geometry} material={materials.elki} position={[0.114, 0.31, -0.129]} rotation={[-0.072, -0.02, 0.272]} />
          <mesh geometry={nodes.Cone3.geometry} material={materials.elki} position={[0.141, -0.173, -0.092]} rotation={[0.043, 0.002, -0.023]} />
          <mesh geometry={nodes.Cone2.geometry} material={materials.elki} position={[0.082, -0.726, -0.051]} rotation={[0.031, -0.004, 0.055]} />
          <mesh geometry={nodes.Cone1.geometry} material={materials.elki} position={[0.037, -1.41, -0.092]} rotation={[-0.075, -0.004, 0.055]} />
          <mesh geometry={nodes.Cone.geometry} material={materials.elki} position={[-0.057, -2.127, 0.039]} rotation={[-0.075, 0, 0]} />
        </group>
      </group>
      <group position={[-1.104, 0.387, 6.37]}>
        <mesh geometry={nodes['Gryadka_s_klubnik0oi1-Mat6'].geometry} material={materials['Mat.6']} />
        <mesh geometry={nodes['Gryadka_s_klubnik0oi1-elki'].geometry} material={materials.elki} />
        <mesh geometry={nodes['Gryadka_s_klubnik0oi1-strawberry'].geometry} material={materials.strawberry} />
      </group>
      <group position={[4.69, 0.497, 2.209]}>
        <mesh geometry={nodes['pumpkins1-Mat4'].geometry} material={materials['Mat.4']} />
        <mesh geometry={nodes['pumpkins1-elki'].geometry} material={materials.elki} />
      </group>
      <group position={[7.907, 3.099, -1.996]} rotation={[Math.PI, -0.038, Math.PI]}>
        <mesh geometry={nodes['Apple_tree1-Mat6'].geometry} material={materials['Mat.6']} />
        <mesh geometry={nodes['Apple_tree1-Mat9'].geometry} material={materials['Mat.9']} />
        <mesh geometry={nodes['Apple_tree1-Mat2'].geometry} material={materials['Mat.2']} />
        <mesh geometry={nodes['Apple_tree1-Mat'].geometry} material={materials.Mat} />
        <mesh geometry={nodes['Apple_tree1-strawberry'].geometry} material={materials.strawberry} />
      </group>
      <group position={[2.179, 1.849, -8.595]} rotation={[-Math.PI, 0.384, -Math.PI]}>
        <mesh geometry={nodes['Birch1-Mat9_1'].geometry} material={materials['Mat.9']} />
        <mesh geometry={nodes['Birch1-Mat_1'].geometry} material={materials.Mat} />
      </group>
      <group position={[4.253, 1.2, 4.16]}>
        <mesh geometry={nodes['kolodec1-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['kolodec1-Mat2'].geometry} material={materials['Mat.2']} />
        <mesh geometry={nodes['kolodec1-Mat9'].geometry} material={materials['Mat.9']} />
        <mesh geometry={nodes['kolodec1-Mat10'].geometry} material={materials['Mat.10']} />
        <mesh geometry={nodes.KolKryshka.geometry} material={materials['Mat.15']} position={[-0.689, 1.606, 2.085]} />
      </group>
      <group position={[-5.499, 3.684, 5.504]}>
        <mesh geometry={nodes['Birch-Mat9_1'].geometry} material={materials['Mat.9']} />
        <mesh geometry={nodes['Birch-Mat_1'].geometry} material={materials.Mat} />
      </group>
      <group position={[-1.114, 5.483, -1.849]}>
        <mesh geometry={nodes['House1-Mat10'].geometry} material={materials['Mat.10']} />
        <mesh geometry={nodes['House1-Mat9'].geometry} material={materials['Mat.9']} />
        <mesh geometry={nodes['House1-Mat3'].geometry} material={materials['Mat.3']} />
        <mesh geometry={nodes['House1-glass'].geometry} material={materials.glass} />
        <mesh geometry={nodes['House1-Mat1'].geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes['House1-Mat2'].geometry} material={materials['Mat.2']} />
      </group>
      <mesh geometry={nodes.path.geometry} material={materials['Mat.8']} position={[4.886, 0.101, 0]}>
        <mesh geometry={nodes.Extrude.geometry} material={materials['Mat.10']} position={[-4.886, -1.568, 0]} />
      </mesh>
      <mesh geometry={nodes.bushFront.geometry} material={materials.elki} position={[6.51, 0.321, 1.065]} />
      <mesh geometry={nodes.bush2.geometry} material={materials.Mat} position={[7.433, 0.33, -1.583]} />
      <mesh geometry={nodes.zabor4.geometry} material={materials['Mat.8']} position={[-1.107, 0.329, 6.449]} />
      <mesh geometry={nodes.kamyshi_trava2.geometry} material={materials.elki} position={[2.128, 0.118, -9.252]} rotation={[0, -0.721, 0]} />
      <mesh geometry={nodes.kamyshi_trava1.geometry} material={materials.elki} position={[-4.858, 0.148, 3.964]} rotation={[0, -0.721, 0]} />
      <mesh geometry={nodes.kamyshi_trava.geometry} material={materials.elki} position={[3.44, 0.164, 5.558]} rotation={[0, -0.721, 0]} />
      <mesh geometry={nodes.oblako_1.geometry} material={materials['Mat.9']} position={[0, -0.679, 0]} rotation={[0, 0, -Math.PI]} />
      <mesh geometry={nodes.stone1_1.geometry} material={materials.stone1} position={[-7.319, -0.038, 5.471]} rotation={[0.227, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/House_kal.glb')
